version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_local
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: chesswiz
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  stockfish:
      image: sf_16
      build: 
        context: .
        dockerfile: Docker_sf_16
      ports:
        - "23249:23249"
      volumes:
        - ./sfdata:/stockfish/data # Optional: mount a local directory to the container
volumes:
  mongodb_data_container: