services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_local
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: chesswiz
    volumes:
      - mongodb_data_container:/data/db
      - ./docker-entrypoint-initdb.d/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
  stockfish:
      image: sf_16
      build: 
        context: .
        dockerfile: Docker_sf_16
      ports:
        - "23249:23249"
      volumes:
        - ./sfdata:/stockfish/data # Optional: mount a local directory to the container
  localstack: 
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=sqs
      - EDGE_PORT=4566
      - DEFAULT_REGION=us-east-1
      - CLEAR_TMP_FOLDER=0
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack/data:/tmp/localstack/data2"
      - "./init.sh:/etc/localstack/init/ready.d/init.sh"
      - "/var/run/docker.sock:/var/run/docker.sock"
    # entrypoint: /docker-entrypoint-initaws.d/init.sh
volumes:
  mongodb_data_container: