version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_local
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: chesswiz
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongodb_data_container:

#  # Database Manager
#   mongo-express:
#     image: mongo-express
#     ports:
#       - 8099:8081
#     depends_on:
#       - mongodb
#     environment:
#       ME_CONFIG_BASICAUTH_USERNAME: express
#       ME_CONFIG_BASICAUTH_PASSWORD: 123456
#       ME_CONFIG_MONGODB_PORT: 27017
#       ME_CONFIG_MONGODB_ADMINUSERNAME: helpdev
#       ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
#     links:
#       - mongodb:mongo


# db.createUser({
#     user: "chesswiz", // Replace with your preferred username
#     pwd: "ch3sswiz", // Replace with a strong password
#     roles: [
#         { role: "readWrite", db: "chesswiz" }
#     ]
# })